<template>
<div id="post">
  <v-singlepost v-bind:post-title="attributes.title" v-bind:post-date="date" v-bind:post-read-time="readtime" v-bind:post-body="content"></v-singlepost>
</div>
</template>

<script>
import SinglePost from '~/components/SinglePost';

// Let's require the needed modules
// dayjs used to convert time to readable form
//var dayjs = require('dayjs');
// prismjs used for highlighting code
//import Prism from 'prismjs';
// add prefix to class name generated by prism, solve
// compatabliity issues with Bulma
//Prism.plugins.customClass.prefix('prism-');

// config markdown-it
/*
const fm = require("front-matter");
var md = require("markdown-it")({
  html: true,
  typographer: true,
  linkify: true,
  highlight: function (str, lang) {
    var languageString = 'language-' + lang;
    if (Prism.languages[lang]) {
      return '<pre class="language-' + lang + '"><code class="language-' + lang + '">' + Prism.highlight(str, Prism.languages[lang], lang) + '</code></pre>';
    } else {
      return '<pre class="language-' + lang + '"><code class="language-' + lang + '">' + Prism.util.encode(str) + '</code></pre>';
    }
  }
});

md.use(require('markdown-it-footnote'));
md.use(require('@iktakahiro/markdown-it-katex'), {"throwOnError" : false, "errorColor" : " #cc0000"});
md.use(require('markdown-it-container'), 'notification');
*/
// disable anchor plugin due to bug
//md.use(require('markdown-it-anchor'));

export default {
  components: {
    'v-singlepost': SinglePost
  },
  async asyncData({ app, params, error }) {
    // We read the markdown file by looking at the `post` parameter
    // in the URL and searching for a markdown file with that name in
    // the posts directory
    const fileContent = await import(`~/contents/posts/${params.post}.md`);
    // We process the raw output through front-matter
    // (markdownit was giving me garbled results)
    let res = app.$fm(fileContent.default);
    //console.log(app.$fm)
    var wordCount = res.body.replace( /[^\w ]/g, "" ).split( /\s+/ ).length;
    //console.log(app.$Prism);
    return {
      // attributes will be an object containing the markdown metadata
      attributes: res.attributes,
      // content will contain the body of the markdown file,
      // rendered in HTML via the `markdownit` class
      content: app.$markdownRenderer.render(res.body),
      // accquire date
      date: app.$dayjs(res.attributes.date).format('MMMM DD,YYYY'),
      // compute estimated read time
      readtime: Math.floor(wordCount / 228) + 1
    };
  },
  head () {
    return {
      link: [
        { rel: 'stylesheet', href: 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css', integrity: 'sha384-yFRtMMDnQtDRO8rLpMIKrtPCD5jdktao2TV19YiZYWMDkUR5GQZR/NOVTdquEx1j', crossorigin: 'anonymous' }
      ]
    }
  },
  layout: 'post',
  mounted () {
    this.$mediumZoom('.content img', { scrollOffset: 0, margin:48 });
    Prism.highlightAll(); // needed to correctly re-render copy-to-clipboard between route change
  }
};
</script>
